services:
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - trance
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    container_name: redis
    networks:
      - trance

  nginx:
    build: nginx
    image: nginx:1.0
    container_name: nginx
    networks:
      - trance
    ports:
      - 80:80
    env_file:
      - ./nginx/.env
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      gateway:
        condition: service_started

  gateway:
    build: gateway
    image: gateway:1.0
    container_name: gateway
    # ports:
    #   - 4000:4000
    networks:
      - trance
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./gateway/app/.env
    volumes:
      - ./gateway/app/:/app
      - /app/node_modules

  auth:
    build: auth
    image: auth:1.0
    container_name: auth
    # ports:
    #   - 3001:3001
    networks:
      - trance
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./auth/app/.env
    volumes:
      - ./auth/app/:/app
      - /app/node_modules

  user:
    build: user
    image: user:1.0
    container_name: user
    networks:
      - trance
    # ports:
    #   - 3002:3002
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./user/app/.env
    volumes:
      - ./user/app/:/app
      - /app/node_modules

  friend:
    build: friend
    image: friend:1.0
    container_name: friend
    networks:
      - trance
    # ports:
    #   - 3006:3006
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./friend/app/.env
    volumes:
      - ./friend/app/:/app
      - /app/node_modules

  chat:
    build: chat
    image: chat:1.0
    container_name: chat
    networks:
      - trance
    # ports:
    #   - 3003:3003
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./chat/app/.env
    volumes:
      - ./chat/app/:/app
      - /app/node_modules

  game:
    build: game
    image: game:1.0
    container_name: game
    networks:
      - trance
    # ports:
    #   - 3004:3004
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./game/app/.env
    volumes:
      - ./game/app/:/app
      - /app/node_modules

  notification:
    build: notification
    image: notification:1.0
    container_name: notification
    networks:
      - trance
    # ports:
    #   - 3005:3005
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./notification/app/.env
    volumes:
      - ./notification/app/:/app
      - /app/node_modules



networks:
  trance:
    name: trance
    driver: bridge
