POST http://localhost:3030/api/auth/signin
Content-Type: application/json

{
    "username": "otman",
    "password": "test"
}

###

POST http://localhost:3030/api/auth/signup
Content-Type: application/json

{
    "username": "aymane",
    "password": "test",
    "email": "aymane@aymane"
}

###



